services:
  # AI model server (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: industrial-rag-ollama
    ports:
      - "11434:11434"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ollama_storage:/root/.ollama

  # FastAPI Backend
  api:
    build: backend/
    container_name: industrial-rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  # Streamlit Frontend
  web:
    build: frontend/
    container_name: industrial-rag-web
    ports:
      - "8501:8501"
    depends_on:
      - api


volumes:
  ollama_storage: